version: '2'
services:
  master:
    tty: true
    build:
      context: master
    command: ["roscore"]

  launch:
    tty: true
    build:
      context: app
    command: ["./launch.sh", "basic_lecture", "pubsub.launch"]
    volumes:
      - ./app:/app
      - /tmp/.X11-unix:/tmp/.X11-unix
    depends_on:
      - master
    environment:
      - ROS_MASTER_URI=http://master:11311
      - DISPLAY=unix$DISPLAY
    ipc: host

  turtlesim:
    tty: true
    build:
      context: app
    command: ["./run.sh", "turtlesim", "turtlesim_node"]
    volumes:
      - ./app:/app
      - /tmp/.X11-unix:/tmp/.X11-unix
    depends_on:
      - master
    environment:
      - ROS_MASTER_URI=http://master:11311
      - DISPLAY=unix$DISPLAY
    ipc: host

  build:
    tty: true
    build:
      context: app
    command: ["catkin_make"]
    volumes:
      - ./app:/app
