version: '2'
services:
  master:
    tty: true
    build:
      context: master
    command: ["roscore"]

  launch:
    tty: true
    build:
      context: app
    command: ["./launch.sh", "basic_lecture", "pubsub.launch"]
    volumes:
      - ./app:/app
    depends_on:
      - master
    environment:
      - ROS_MASTER_URI=http://master:11311

  build:
    tty: true
    build:
      context: app
    command: ["catkin_make"]
    volumes:
      - ./app:/app
